apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
data:
  {{ .Values.config.name }}: |
  {{- $path := ( printf "config/%v/appsettings.json"  .Values.app.env ) }}
  {{- .Files.Get $path | nindent 4 }}