apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: etixqa
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "harbor.corp.det.gov.ae/eticketing.io/apps/authapi:1.0.0"
        ports:
        - containerPort: 3021
