# Default values for authapi cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

app:
  namespace: etixqa
  name: etixapp
  env: qa
  
  # default asp.netcore environment configuration
  asp_env: Development
  
  # pods replicas
  replicas: 1  
  
  container:
    image: atmetix.azurecr.io/authapi:66
    image_Pull_Policy: IfNotPresent 
    port: 3021
    
  computerc:
    limits:
      cpu: 0.2
      memory: "512Mi"
    requests:
      cpu: 0.2
      memory: "512Mi"
      
  service:
    port: 80
    targetPort: 80

config:
  name: appsettings.json
  
secret:
  name: appsettings.secrets.json