apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi-deployment
  labels:
    app: authapi
spec:
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - name: authapi
        image: hello-world-notfund
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m