apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  {{ .Values.secret.name }}: |
  {{- $path := ( printf "config/%v/appsettings.secrets.json"  .Values.app.env ) }}
  {{- .Files.Get $path | nindent 4 }}
